language: python
python:
  - "3.6"
  - "3.5"
before_install:
  - git clone https://github.com/chris104957/django-carrot.git
  - cd django-carrot
  - pip install -r requirements.txt
  - pip install django==$DJANGO_VERSION

install:
  - python setup.py sdist
  - pip install --upgrade dist/*.gz
script:
  - coverage run run_tests.py
after_success:
  - coveralls
deploy:
  provider: pypi
  user: "chris140957"
  password:
    secure: jLw1CiHUTfRXCBZlpG4usYKz1lLl+5RQLJgzCIAZmgjDgQU0RbANq0clLo8Hgyn8yRneKvCwGFvgwTpj7N72AE2I3GUqPIKu68Zk3Svb+7EJSNYkbXIk4XeergAEV0LpYgOix5ZlbliN2eWMNlNX+s4KD+ZnG/2O1fbTYMYjOamuTd4Bpnp6cIxt7RSVgTtPUPL3yOKQVihB6yqUdRzcnIRPvMVIRCzuIzTmaXx9Bc/uRr3AKlZg/suVQCTJAEmFuj/OynSfHBiwlJq/b4TKXhQBXofhVLIMOyd1iSRa6jA8r5UUodMVTCUYLj3neCsT5Idm0aHT/xJ5meMQczGZS++9ZiS/jx7u0rd37qmj++GEurH8139c18FQa9GJRCV63xfsuLP9/DlGbmkuzD91IruFwSbp0OUbJVstjjx8lV3pxtSson6Q8PU4Ua0AR1c/dEEiB1M4Wo7vcgBg+i7jv23NOwNmArIbVbLRk7z7ZbPaHwu0AGhoMmVuOJzUmuyNaxnX516qzinVnQ9GTKBceXSelcYkwk+7Wb7qCb8eALlay3l8DZqHu4b2mauJ0dhkp5l4LhM9TdGgOR13RRWaQ0b9r8r8TGDEf9qy0sp14IXtar3aOKdeImQyeDtu4zP2svs5qXr9sC7l21POfppCr+r/oOPfyQJty1YdYzNTtqU=
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
