language: python
python:
  - "3.6"
install:
  - pip install -e .
before_script:
  - pip install -r requirements.txt
  - git clone https://github.com/chris104957/django-carrot.git
  - cd django-carrot
script:
  - coverage run run_tests.py
  - pwd
  - coveralls
env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5
  - DJANGO_VERSION=2.0
