language: python
python:
  - "3.6"
  - "3.5"
before_install:
  - git clone https://github.com/chris104957/django-carrot.git
  - cd django-carrot
  - pip install -r requirements.txt
  - pip install django==$DJANGO_VERSION

install:
  - python setup.py sdist
  - pip install --upgrade dist/*.gz
script:
  - coverage run run_tests.py
after_success:
  - coveralls
env:
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10
  - DJANGO_VERSION=1.11
  - DJANGO_VERSION=2.0
