language: python
python:
  - "3.6"
before_install:
  - pip install -r requirements.txt
  - git clone https://github.com/chris104957/django-carrot.git
  - cd django-carrot
install:
  - pip install -e .
script:
  - coverage run run_tests.py
after_success:
  - coveralls -u https://coveralls.io/github/chris104957/django-carrot
env:
  - DJANGO_VERSION=1.10.8
  - DJANGO_VERSION=1.11.5
  - DJANGO_VERSION=2.0
