language: python

python:
  - "3.6"

before_install:
  - pip install poetry

install:
  - poetry install

script:
  - coverage run run_tests.py

after_success:
  - coveralls

before_deploy:
  - poetry config repositories.packagr https://api.packagr.app/63cdQSDO/
  - poetry config http-basic.packagr "christopherdavies553@gmail.com" $PACKAGR_PASSWORD
  - poetry config http-basic.pypi chris140957 $PACKAGR_PASSWORD

deploy:
  - provider: script
    script: poetry publish --build
    on:
      tags: true

  - provider: script
    script: poetry publish --build -r packagr
    on:
      all_branches: true
