language: python
python:
  - "3.6"
before_install:
  - git clone https://github.com/chris104957/django-carrot.git
  - cd django-carrot
  - pip install -r requirements.txt

install:
  - python3 setup.py sdist
  - sudo pip3 install --upgrade dist/*.gz
script:
  - coverage run run_tests.py
after_success:
  - coveralls
env:
#  - DJANGO_VERSION=1.10.8
#  - DJANGO_VERSION=1.11.5
  - DJANGO_VERSION=2.0
